# Generated by Django 4.2.5 on 2023-10-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinica',
        ),
    ]
