# Generated by Django 4.2.5 on 2023-10-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_delete_inicio_estudio_edad_estudio_especie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='raza',
        ),
        migrations.AddField(
            model_name='turno',
            name='apellido',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='consulta',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='turno',
            name='dia',
            field=models.DateField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='raza',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='raza',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='especie',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
