# Generated by Django 4.2.6 on 2023-10-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0007_cirugia_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.CharField(max_length=50),
        ),
    ]
